ALTER TABLE ALLOCATION_CATEGORY_OPTION_LEVEL ADD (OPTIONS_LIMIT bigint DEFAULT 5);
ALTER TABLE ALLOCATION_COUNTRY_CATEGORY_OPTION_LEVEL ADD (OPTIONS_LIMIT bigint DEFAULT 5);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-134', 'add column Option Limit to table ALLOCATION_CATEGORY_OPTION_LEVEL and ALLOCATION_COUNTRY_CATEGORY_OPTION_LEVEL', 'V2001803261200__Add_Column_Option_Limit.sql');

COMMIT;

