ALTER TABLE EXPECTED_OUTCOME_LEVEL ADD (KPI_DISTRIBUTION TINYINT DEFAULT 0);

UPDATE EXPECTED_OUTCOME_LEVEL SET
KPI_DISTRIBUTION = 1
WHERE HIERARCHY_LEVEL_ID IN (2,3)
AND EXPECTED_OUTCOME_OPTION_ID IN (SELECT EXPECTED_OUTCOME_OPTION_ID FROM EXPECTED_OUTCOME_OPTION WHERE NAME = 'MNP')
AND EXPECTED_OUTCOME_ID IN (SELECT EXPECTED_OUTCOME_ID FROM EXPECTED_OUTCOME WHERE NAME = 'Campaign Forecasting')
AND ENABLED = 1
AND DELETED = 0;

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-138', 'add column KPI distribution to EXPECTED_OUTCOME_LEVEL', 'V2001804131200__Add_Column_Kpi_Distribution.sql');

COMMIT;

