ALTER TABLE "MKTG_PLANNING_TOOL"."HL6_LEGACY" ADD (HL6_ID BIGINT);

ALTER TABLE HL6_LEGACY ALTER ( HL6_CRM_DESCRIPTION NVARCHAR ( 100 ) NULL  );
ALTER TABLE HL6_LEGACY ALTER ( PATH NVARCHAR ( 25 ) NULL  );
ALTER TABLE HL6_LEGACY ALTER ( BUDGET DECIMAL ( 19,2 ) NULL  );
ALTER TABLE HL6_LEGACY ALTER ( IN_BUDGET TINYINT    NULL  );
ALTER TABLE HL6_LEGACY ALTER ( BUDGET_SPEND_Q1 DECIMAL ( 19,2 ) NULL  );
ALTER TABLE HL6_LEGACY ALTER ( BUDGET_SPEND_Q2 DECIMAL ( 19,2 ) NULL  );
ALTER TABLE HL6_LEGACY ALTER ( BUDGET_SPEND_Q3 DECIMAL ( 19,2 ) NULL  );
ALTER TABLE HL6_LEGACY ALTER ( BUDGET_SPEND_Q4 DECIMAL ( 19,2 ) NULL  );
ALTER TABLE HL6_LEGACY ALTER ( EURO_CONVERSION_ID BIGINT    NULL  );
ALTER TABLE HL6_LEGACY ALTER ( HL6_STATUS_DETAIL_ID BIGINT    NULL  );
ALTER TABLE HL6_LEGACY ALTER ( CREATED_USER_ID BIGINT    NULL  );
ALTER TABLE HL6_LEGACY ALTER ( RESULTS_CAMPAIGN_Q1 DECIMAL ( 19,2 ) NULL DEFAULT 0 );
ALTER TABLE HL6_LEGACY ALTER ( RESULTS_CAMPAIGN_Q2 DECIMAL ( 19,2 ) NULL DEFAULT 0 );
ALTER TABLE HL6_LEGACY ALTER ( RESULTS_CAMPAIGN_Q3 DECIMAL ( 19,2 ) NULL DEFAULT 0 );
ALTER TABLE HL6_LEGACY ALTER ( RESULTS_CAMPAIGN_Q4 DECIMAL ( 19,2 ) NULL DEFAULT 0 );
ALTER TABLE HL6_LEGACY ALTER ( CO_FUNDED TINYINT NULL DEFAULT 0 );
ALTER TABLE HL6_LEGACY ALTER ( IS_COMPLETE TINYINT NULL DEFAULT 0 );

ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ALTER (HL5_ID BIGINT null);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6_IN_CRM_VERSION" ALTER (HL5_ID BIGINT null);


-- **** ADD PARENT_PATH to avoid duplcated acronyms

ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (PARENT_PATH NVARCHAR(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" DROP CONSTRAINT UK_HL6_CRM_ID;
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD CONSTRAINT UK_HL6_CRM_ID UNIQUE(HL5_ID, ACRONYM, DELETED_TOKEN, PARENT_PATH);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-158', 'Support L6 Legacy Creation Edition', 'V2001805241650__Support_L6_Legacy_Creation_Edition report_Implement_New_Mechanism_To_Identify_Changes_Update_In_Crm_Version.sql');

COMMIT;

