-- ********************* HL5 ********************* --
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5"
DROP(TARGET_AUDIENCE_ID);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL5_TARGET_AUDIENCE"(
	"HL5_TARGET_AUDIENCE_ID" bigint not null primary key generated by default as IDENTITY,
	"TARGET_AUDIENCE_ID" BIGINT NOT NULL,
	"HL5_ID" BIGINT NOT NULL,

	"CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
    "MODIFIED_DATE_TZ" timestamp,
    "CREATED_USER_ID" bigint not null,
    "MODIFIED_USER_ID" bigint,
    "ENABLED" tinyint default 1,
    "DELETED" tinyint default 0,

	FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
	FOREIGN KEY ("HL5_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL5"("HL5_ID"),
	FOREIGN KEY ("TARGET_AUDIENCE_ID") REFERENCES "MKTG_PLANNING_TOOL"."TARGET_AUDIENCE"("TARGET_AUDIENCE_ID")
);

-- ********************* HL6 ********************* --
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6"
DROP(TARGET_AUDIENCE_ID);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL6_TARGET_AUDIENCE"(
	"HL6_TARGET_AUDIENCE_ID" bigint not null primary key generated by default as IDENTITY,
	"TARGET_AUDIENCE_ID" BIGINT NOT NULL,
	"HL6_ID" BIGINT NOT NULL,

	"CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
    "MODIFIED_DATE_TZ" timestamp,
    "CREATED_USER_ID" bigint not null,
    "MODIFIED_USER_ID" bigint,
    "ENABLED" tinyint default 1,
    "DELETED" tinyint default 0,

	FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
	FOREIGN KEY ("HL6_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL6"("HL6_ID"),
	FOREIGN KEY ("TARGET_AUDIENCE_ID") REFERENCES "MKTG_PLANNING_TOOL"."TARGET_AUDIENCE"("TARGET_AUDIENCE_ID")
);
-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-187', 'Make Target Audience a Multi-Select attribute - L5/L6', 'V201911271550__Make_Target_Audience_Multi_Select_Event_Planning_Form.sql');

COMMIT;
