/* 
***************** IMPORTANT!! ************************
Make sure to delete the constraint in order to delete the 'USER_ID_SEND_MAIL' column

- Search the constraint name (search for the MKTG_PLANNING_TOOL one)

select * from "REFERENTIAL_CONSTRAINTS"
where TABLE_NAME = 'HL4'
order by COLUMN_NAME

- Delete the constraint:

ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP CONSTRAINT _SYS_CONSTRAINT_783625_#16_#F0; 

*/
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (USER_ID_SEND_MAIL); -- Do the steps above before this

ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (IS_HL4);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (HL4_PARENT_ID);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (COMMENTS);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (IS_SEND_MAIL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (READ_ONLY);

ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (HL4_FNC_BUDGET_SPEND_Q1);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (HL4_FNC_BUDGET_SPEND_Q2);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (HL4_FNC_BUDGET_SPEND_Q3);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" DROP (HL4_FNC_BUDGET_SPEND_Q4);

RENAME COLUMN "MKTG_PLANNING_TOOL"."HL4".HL4_FNC_BUDGET_TOTAL_MKT to BUDGET;

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-156', 'Removed depretated HL4 Columns', 'V201805160950__Removed_deprecated_hl4_columns.sql');

COMMIT;