ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (EMPLOYEE_RESPONSIBLE_USER NVARCHAR(7));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (EMPLOYEE_RESPONSIBLE_USER NVARCHAR(7));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (PERSON_RESPONSIBLE NVARCHAR(7));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (PERSON_RESPONSIBLE NVARCHAR(7));

-- Update schema version
INSERT INTO "MKTG_PLANNING_TOOL"."SCHEMA_VERSION"(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-75', 'Add new column EMPLOYEE_RESPONSIBLE_USER to HL5 AND HL6 table', 'V201710191100__Add_Employee_Responsible_User.sql');

COMMIT;