ALTER TABLE "MKTG_PLANNING_TOOL"."OBJECTIVE" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."OBJECTIVE" add(DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."CAMPAIGN_TYPE" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."CAMPAIGN_TYPE" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."CAMPAIGN_SUB_TYPE" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."CAMPAIGN_SUB_TYPE" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."BUSINESS_OWNER" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."BUSINESS_OWNER" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."PRIORITY" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."PRIORITY" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."SALE_ORGANIZATION" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."SALE_ORGANIZATION" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."DISTRIBUTION_CHANNEL" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."DISTRIBUTION_CHANNEL" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."ROUTE_TO_MARKET" ADD ("CRM_KEY" nvarchar(15));
alter table "MKTG_PLANNING_TOOL"."ROUTE_TO_MARKET" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."ALLOCATION_OPTION" ADD ("CRM_KEY" nvarchar(50));
alter table "MKTG_PLANNING_TOOL"."ALLOCATION_OPTION" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "MKTG_PLANNING_TOOL"."OBJECTIVE" ADD CONSTRAINT UK_OBJECTIVE_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."CAMPAIGN_TYPE" ADD CONSTRAINT UK_CAMPAIGN_TYPE_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."CAMPAIGN_SUB_TYPE" ADD CONSTRAINT UK_CAMPAIGN_SUB_TYPE_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."BUSINESS_OWNER" ADD CONSTRAINT UK_BUSINESS_OWNER_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."PRIORITY" ADD CONSTRAINT UK_PRIORITY_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SALE_ORGANIZATION" ADD CONSTRAINT UK_SALE_ORGANIZATION_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."DISTRIBUTION_CHANNEL" ADD CONSTRAINT UK_DISTRIBUTION_CHANNEL_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."ROUTE_TO_MARKET" ADD CONSTRAINT UK_ROUTE_TO_MARKET_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."ALLOCATION_OPTION" ADD CONSTRAINT UK_ALLOCATION_OPTION_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);

--drop unused table
DROP TABLE "MKTG_PLANNING_TOOL"."CAMPAIGN_SUBTYPE";

-- Update schema version
INSERT INTO "MKTG_PLANNING_TOOL"."SCHEMA_VERSION"(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-70', 'Upload CRM KEY in tables', 'V201710051100__CRM_KEY.sql');

COMMIT;