--Sales Segmentation (SEGMENTATION_SALES)
create COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_SALES" (
    SEGMENTATION_SALES_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    PARENT_ID BIGINT,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);
--***************************************

--/*SEGMENTATION_MARKET*/
CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_MARKET" (
	SEGMENTATION_MARKET_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
	deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

--Region Buying Segmentation (SEGMENTATION_REGION_BUYING)
create COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_REGION_BUYING" (
    SEGMENTATION_REGION_BUYING_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

--CREATE SEGMENTATION_ALLOCATION_OPTION
create column table "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY" (
	SEGMENTATION_CATEGORY_ID bigint not null primary key generated by default as IDENTITY,
	name nvarchar(255) NOT NULL,
	ALLOCATION_CATEGORY_ID BIGINT NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
	FOREIGN KEY ("ALLOCATION_CATEGORY_ID") REFERENCES "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY"("ALLOCATION_CATEGORY_ID"),
    FOREIGN KEY (created_user_id) REFERENCES "MKTG_PLANNING_TOOL".USER(user_id)
);
--insert Industries data
insert into "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY"(name, ALLOCATION_CATEGORY_ID, created_user_id)
select name, ALLOCATION_CATEGORY_ID, created_user_id
from "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY"
where upper(NAME) = 'INDUSTRIES'
and enabled = 1 and deleted = 0;

-- SEGMENTATION_CATEGORY_OPTION to save allocations options
CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY_OPTION" (
	SEGMENTATION_CATEGORY_OPTION_ID bigint not null primary key generated by default as IDENTITY,
	SEGMENTATION_CATEGORY_ID BIGINT NOT NULL,
	name nvarchar(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
	deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
    FOREIGN KEY ("SEGMENTATION_CATEGORY_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY"("SEGMENTATION_CATEGORY_ID")
);

--inserting data from ALLOCATION_CATEGORY_OPTION_LEVEL getting from HL5 configuration and category name Industries
insert into "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY_OPTION"
(SEGMENTATION_CATEGORY_ID, NAME, CREATED_USER_ID)
select sc.SEGMENTATION_CATEGORY_ID, ao.NAME, acol.created_user_id--, acol.ALLOCATION_OPTION_ID
from "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL" acol
inner join "MKTG_PLANNING_TOOL"."ALLOCATION_OPTION" ao on ao.ALLOCATION_OPTION_ID = acol.ALLOCATION_OPTION_ID
inner join "MKTG_PLANNING_TOOL"."HIERARCHY_LEVEL" hl on hl.HIERARCHY_LEVEL_ID = acol.HIERARCHY_LEVEL_ID
inner join "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY" sc on sc.ALLOCATION_CATEGORY_ID = acol.ALLOCATION_CATEGORY_ID
where
acol.enabled = 1 and acol.deleted = 0
and hl.description = 'HL5';

create COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FUNCTION" (
    SEGMENTATION_FUNCTION_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    PARENT_ID BIGINT,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

create COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_DEPARTMENT" (
    SEGMENTATION_DEPARTMENT_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    PARENT_ID BIGINT,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

--Item of Interest Segmentation (SEGMENTATION_ITEM_INTEREST)
create COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_ITEM_INTEREST" (
    SEGMENTATION_ITEM_INTEREST_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

--Tactic Segmentation (SEGMENTATION_TACTIC)
create COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_TACTIC" (
    SEGMENTATION_TACTIC_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

-- add CONSTRAINT unique
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_SALES" ADD CONSTRAINT UK_SEGMENTATION_SALES_NAME UNIQUE(NAME, PARENT_ID, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_MARKET" ADD CONSTRAINT UK_SEGMENTATION_MARKET_NAME UNIQUE(NAME, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_REGION_BUYING" ADD CONSTRAINT UK_SEGMENTATION_REGION_BUYING_NAME UNIQUE(NAME, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY_OPTION" ADD CONSTRAINT UK_SEGMENTATION_CATEGORY_OPTION_NAME UNIQUE(NAME, SEGMENTATION_CATEGORY_ID, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FUNCTION" ADD CONSTRAINT UK_SEGMENTATION_FUNCTION_NAME UNIQUE(NAME, PARENT_ID, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_DEPARTMENT" ADD CONSTRAINT UK_SEGMENTATION_DEPARTMEN_NAME UNIQUE(NAME, PARENT_ID, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_ITEM_INTEREST" ADD CONSTRAINT UK_SEGMENTATION_ITEM_INTEREST_NAME UNIQUE(NAME, DELETED_TOKEN);
ALTER TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_TACTIC" ADD CONSTRAINT UK_SSEGMENTATION_TACTIC_NAME UNIQUE(NAME, DELETED_TOKEN);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."COUNTRY" (
    COUNTRY_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."PARTNER" (
    PARTNER_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."COMPETITOR" (
    COMPETITOR_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."UNQUALIFIED_ADDRESS" (
    UNQUALIFIED_ADDRESS_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."ACCOUNT_WITH_ACTIVE_PIPELINE" (
    ACCOUNT_WITH_ACTIVE_PIPELINE_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."ACCOUNT_WITH_ACTIVE_LEAD" (
    ACCOUNT_WITH_ACTIVE_LEAD_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."MATCH_CRITERIA" (
    MATCH_CRITERIA_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

INSERT INTO MATCH_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Only Companies' ,1);
INSERT INTO MATCH_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Companies and Contacs' ,1);
INSERT INTO MATCH_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Only Contacts' ,1);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."TARGET_SELECT_CRITERIA" (
    TARGET_SELECT_CRITERIA_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    NAME NVARCHAR(255) NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

INSERT INTO TARGET_SELECT_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Overview of companies which have contacts' ,1);
INSERT INTO TARGET_SELECT_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Contacts for specific companies ( company Ids to be provided by requestor)', 1);
INSERT INTO TARGET_SELECT_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Companies and contacs list (no IDs are provided)', 1);
INSERT INTO TARGET_SELECT_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Companies and contacs list with CRM IDs provided', 1);
INSERT INTO TARGET_SELECT_CRITERIA(NAME, CREATED_USER_ID) VALUES ('Overview ofall  companies with or without contacts', 1);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."FORM_STATUS_DETAIL" (
    FORM_STATUS_DETAIL_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	 DETAIL NVARCHAR(255) NOT NULL ,
	 CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	 MODIFIED_DATE_TZ TIMESTAMP,
	 CREATED_USER_ID BIGINT NOT NULL ,
	 MODIFIED_USER_ID BIGINT,
	 ENABLED TINYINT DEFAULT 1,
	 DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
 );

 INSERT INTO FORM_STATUS_DETAIL(DETAIL, CREATED_USER_ID) VALUES ('Draft', 1);
 INSERT INTO FORM_STATUS_DETAIL(DETAIL, CREATED_USER_ID) VALUES ('Complete', 1);

--SEGMENTATION_FORM section
CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM" (
    SEGMENTATION_FORM_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    FORM_STATUS_DETAIL_ID BIGINT NOT NULL,
    SERVICE_REQUEST_CATEGORY_OPTION_LEVEL_ID BIGINT NOT NULL,
    HL5_ID BIGINT NOT NULL,
    REGION_ID BIGINT,
    SUBREGION_ID BIGINT,
    COUNTRY BIGINT,
    HL4_ID BIGINT NOT NULL,
    TARGET_GROUP_APPROVAL_WORKFLOW TINYINT,
    MATCHING_REQUIRED TINYINT,
    MATCH_CRITERIA_ID BIGINT,
    NUMBER_OF_RECORD_NEED_MATCHING INTEGER,
    TARGET_SELECT_CRITERIA_ID BIGINT,
    SPECIAL_NOTE NVARCHAR(1000),
    ATTACHMENT_ID BIGINT,
    REVENUE_RANGE_FROM NVARCHAR(1000),
    REVENUE_RANGE_TO NVARCHAR(1000),
    CURRENCY_ID bigint,
    NUMBER_OF_EMPLOYEE_FROM INTEGER,
    NUMBER_OF_EMPLOYEE_TO INTEGER,
    CUSTOMER_STATUS_ID INTEGER,
    REGIONAL_BUYING_CLASSIFICATION_ID BIGINT,
    COMPETITOR_ID BIGINT,
    PARTNER_ID BIGINT,
    UNQUALIFIED_ADDRESS_ID BIGINT,
    ACCOUNT_WITH_ACTIVE_PIPELINE_ID BIGINT,
    ACCOUNT_WITH_ACTIVE_LEAD_ID BIGINT,
    CONTACT_DETAIL NVARCHAR(1000),
    MAX_CONTACT_PER_ORGANIZATION INTEGER,
    EXCLUDE_CONTACS_TOUCHED_BY_TELEMARKETING INTEGER,
    APPLY_SALE_PLAY_FOR_TARGET TINYINT,
    APPLY_PREDICTIVE_ANALYTICS_FOR_TARGET TINYINT,
    SUMMARY NVARCHAR(255),
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SERVICE_REQUEST_CATEGORY_OPTION_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."SERVICE_REQUEST_CATEGORY_OPTION_LEVEL"("SERVICE_REQUEST_CATEGORY_OPTION_LEVEL_ID"),
    FOREIGN KEY ("HL5_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL5"("HL5_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM_SEGMENTATION_MARKET" (
    SEGMENTATION_FORM_SEGMENTATION_MARKET_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SEGMENTATION_FORM_ID BIGINT NOT NULL,
    SEGMENTATION_MARKET_ID BIGINT NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SEGMENTATION_FORM_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM"("SEGMENTATION_FORM_ID"),
    FOREIGN KEY ("SEGMENTATION_MARKET_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_MARKET"("SEGMENTATION_MARKET_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM_SEGMENTATION_SALE" (
    SEGMENTATION_FORM_SEGMENTATION_SALE_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SEGMENTATION_FORM_ID BIGINT NOT NULL,
    SEGMENTATION_SALE_ID BIGINT NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SEGMENTATION_FORM_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM"("SEGMENTATION_FORM_ID"),
    FOREIGN KEY ("SEGMENTATION_SALE_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_SALES"("SEGMENTATION_SALES_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM_SEGMENTATION_INDUSTRY_OPTION" (
    SEGMENTATION_FORM_SEGMENTATION_INDUSTRY_OPTION_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SEGMENTATION_FORM_ID BIGINT NOT NULL,
    SEGMENTATION_INDUSTRY_OPTION_ID BIGINT NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SEGMENTATION_FORM_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM"("SEGMENTATION_FORM_ID"),
    FOREIGN KEY ("SEGMENTATION_INDUSTRY_OPTION_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY_OPTION"("SEGMENTATION_CATEGORY_OPTION_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM_SEGMENTATION_FUNCTION" (
    SEGMENTATION_FORM_SEGMENTATION_FUNCTION_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SEGMENTATION_FORM_ID BIGINT NOT NULL,
    SEGMENTATION_FUNCTION_ID BIGINT NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SEGMENTATION_FORM_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM"("SEGMENTATION_FORM_ID"),
    FOREIGN KEY ("SEGMENTATION_FUNCTION_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FUNCTION"("SEGMENTATION_FUNCTION_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM_SEGMENTATION_DEPARTMENT" (
    SEGMENTATION_FORM_SEGMENTATION_DEPARTMENT_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SEGMENTATION_FORM_ID BIGINT NOT NULL,
    SEGMENTATION_DEPARTMENT_ID BIGINT NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SEGMENTATION_FORM_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM"("SEGMENTATION_FORM_ID"),
    FOREIGN KEY ("SEGMENTATION_DEPARTMENT_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_DEPARTMENT"("SEGMENTATION_DEPARTMENT_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM_SEGMENTATION_TACTIC" (
    SEGMENTATION_FORM_SEGMENTATION_TACTIC_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SEGMENTATION_FORM_ID BIGINT NOT NULL,
    SEGMENTATION_TACTIC_ID BIGINT NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SEGMENTATION_FORM_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM"("SEGMENTATION_FORM_ID"),
    FOREIGN KEY ("SEGMENTATION_TACTIC_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_TACTIC"("SEGMENTATION_TACTIC_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM_SEGMENTATION_ITEM_OF_INTEREST" (
    SEGMENTATION_FORM_SEGMENTATION_ITEM_OF_INTEREST_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    SEGMENTATION_FORM_ID BIGINT NOT NULL,
    SEGMENTATION_ITEM_OF_INTEREST_ID BIGINT NOT NULL,
    CREATED_DATE_TZ TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE_TZ TIMESTAMP,
    CREATED_USER_ID BIGINT NOT NULL,
    MODIFIED_USER_ID BIGINT,
    ENABLED TINYINT DEFAULT 1,
    DELETED TINYINT DEFAULT 0,
    FOREIGN KEY ("SEGMENTATION_FORM_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_FORM"("SEGMENTATION_FORM_ID"),
    FOREIGN KEY ("SEGMENTATION_ITEM_OF_INTEREST_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_ITEM_INTEREST"("SEGMENTATION_ITEM_INTEREST_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

-- List of countries
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (1, 'Afghanistan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (2, 'Albania', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (3, 'Algeria', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (4, 'American Samoa', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (5, 'Andorra', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (6, 'Angola', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (7, 'Anguilla', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (8, 'Antarctica', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (9, 'Antigua and Barbuda', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (10, 'Argentina', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (11, 'Armenia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (12, 'Aruba', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (13, 'Australia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (14, 'Austria', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (15, 'Azerbaijan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (16, 'Bahamas', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (17, 'Bahrain', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (18, 'Bangladesh', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (19, 'Barbados', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (20, 'Belarus', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (21, 'Belgium', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (22, 'Belize', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (23, 'Benin', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (24, 'Bermuda', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (25, 'Bhutan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (26, 'Bolivia Plurinational State of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (27, 'Bonaire  Sint Eustatius and Saba', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (28, 'Bosnia and Herzegovina', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (29, 'Botswana', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (30, 'Bouvet Island', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (31, 'Brazil', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (32, 'British Indian Ocean Territory', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (33, 'Brunei Darussalam', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (34, 'Bulgaria', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (35, 'Burkina Faso', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (36, 'Burundi', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (37, 'Cambodia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (38, 'Cameroon', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (39, 'Canada', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (40, 'Cape Verde', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (41, 'Cayman Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (42, 'Central African Republic', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (43, 'Chad', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (44, 'Chile', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (45, 'China', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (46, 'Christmas Island', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (47, 'Cocos (Keeling) Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (48, 'Colombia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (49, 'Comoros', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (50, 'Congo', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (51, 'Congo the Democratic Republic of the', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (52, 'Cook Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (53, 'Costa Rica', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (54, 'Ivory Coast', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (55, 'Croatia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (56, 'Cuba', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (57, 'Curacao', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (58, 'Cyprus', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (59, 'Czech Republic', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (60, 'Denmark', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (61, 'Djibouti', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (62, 'Dominica', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (63, 'Dominican Republic', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (64, 'Ecuador', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (65, 'Egypt', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (66, 'El Salvador', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (67, 'Equatorial Guinea', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (68, 'Eritrea', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (69, 'Estonia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (70, 'Ethiopia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (71, 'Falkland Islands (Malvinas)', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (72, 'Faroe Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (73, 'Fiji', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (74, 'Finland', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (75, 'France', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (76, 'French Guiana', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (77, 'French Polynesia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (78, 'French Southern Territories', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (79, 'Gabon', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (80, 'Gambia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (81, 'Georgia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (82, 'Germany', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (83, 'Ghana', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (84, 'Gibraltar', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (85, 'Greece', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (86, 'Greenland', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (87, 'Grenada', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (88, 'Guadeloupe', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (89, 'Guam', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (90, 'Guatemala', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (91, 'Guernsey', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (92, 'Guinea', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (93, 'Guinea-Bissau', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (94, 'Guyana', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (95, 'Haiti', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (96, 'Heard Island and McDonald Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (97, 'Holy See (Vatican City State)', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (98, 'Honduras', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (99, 'Hong Kong', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (100, 'Hungary', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (101, 'Iceland', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (102, 'India', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (103, 'Indonesia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (104, 'Iran Islamic Republic of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (105, 'Iraq', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (106, 'Ireland', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (107, 'Isle of Man', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (108, 'Israel', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (109, 'Italy', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (110, 'Jamaica', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (111, 'Japan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (112, 'Jersey', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (113, 'Jordan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (114, 'Kazakhstan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (115, 'Kenya', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (116, 'Kiribati', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (117, 'Korea Democratic Republic of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (118, 'Korea Republic of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (119, 'Kuwait', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (120, 'Kyrgyzstan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (121, 'Lao Democratic Republic of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (122, 'Latvia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (123, 'Lebanon', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (124, 'Lesotho', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (125, 'Liberia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (126, 'Libya', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (127, 'Liechtenstein', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (128, 'Lithuania', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (129, 'Luxembourg', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (130, 'Macao', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (131, 'Macedonia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (132, 'Madagascar', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (133, 'Malawi', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (134, 'Malaysia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (135, 'Maldives', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (136, 'Mali', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (137, 'Malta', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (138, 'Marshall Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (139, 'Martinique', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (140, 'Mauritania', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (141, 'Mauritius', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (142, 'Mayotte', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (143, 'Mexico', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (144, 'Micronesia Federated States of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (145, 'Moldova Republic of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (146, 'Monaco', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (147, 'Mongolia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (148, 'Montenegro', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (149, 'Montserrat', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (150, 'Morocco', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (151, 'Mozambique', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (152, 'Myanmar', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (153, 'Namibia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (154, 'Nauru', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (155, 'Nepal', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (156, 'Netherlands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (157, 'New Caledonia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (158, 'New Zealand', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (159, 'Nicaragua', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (160, 'Niger', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (161, 'Nigeria', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (162, 'Niue', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (163, 'Norfolk Island', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (164, 'Northern Mariana Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (165, 'Norway', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (166, 'Oman', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (167, 'Pakistan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (168, 'Palau', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (169, 'Palestine', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (170, 'Panama', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (171, 'Papua New Guinea', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (172, 'Paraguay', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (173, 'Peru', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (174, 'Philippines', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (175, 'Pitcairn', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (176, 'Poland', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (177, 'Portugal', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (178, 'Puerto Rico', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (179, 'Qatar', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (180, 'Romania', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (181, 'Russian Federation', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (182, 'Rwanda', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (183, 'Saint Barth', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (184, 'Saint Helena Ascension and Tristan da Cunha', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (185, 'Saint Kitts and Nevis', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (186, 'Saint Lucia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (187, 'Saint Martin (French part)', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (188, 'Saint Pierre and Miquelon', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (189, 'Saint Vincent and the Grenadines', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (190, 'Samoa', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (191, 'San Marino', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (192, 'Sao Tome and Principe', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (193, 'Saudi Arabia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (194, 'Senegal', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (195, 'Serbia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (196, 'Seychelles', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (197, 'Sierra Leone', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (198, 'Singapore', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (199, 'Sint Maarten (Dutch part)', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (200, 'Slovakia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (201, 'Slovenia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (202, 'Solomon Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (203, 'Somalia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (204, 'South Africa', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (205, 'South Georgia and the South Sandwich Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (206, 'South Sudan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (207, 'Spain', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (208, 'Sri Lanka', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (209, 'Sudan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (210, 'Suriname', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (211, 'Svalbard and Jan Mayen', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (212, 'Swaziland', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (213, 'Sweden', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (214, 'Switzerland', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (215, 'Syrian Arab Republic', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (216, 'Taiwan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (217, 'Tajikistan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (218, 'Tanzania', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (219, 'Thailand', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (220, 'Timor-Leste', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (221, 'Togo', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (222, 'Tokelau', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (223, 'Tonga', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (224, 'Trinidad and Tobago', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (225, 'Tunisia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (226, 'Turkey', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (227, 'Turkmenistan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (228, 'Turks and Caicos Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (229, 'Tuvalu', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (230, 'Uganda', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (231, 'Ukraine', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (232, 'United Arab Emirates', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (233, 'United Kingdom', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (234, 'United States', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (235, 'United States Minor Outlying Islands', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (236, 'Uruguay', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (237, 'Uzbekistan', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (238, 'Vanuatu', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (239, 'Venezuela Bolivarian Republic of', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (240, 'Viet Nam', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (241, 'Virgin Islands British', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (242, 'Virgin Islands U.S.', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (243, 'Wallis and Futuna', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (244, 'Western Sahara', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (245, 'Yemen', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (246, 'Zambia', 1);
insert into "MKTG_PLANNING_TOOL"."COUNTRY" (country_id, name, created_user_id) values (247, 'Zimbabwe', 1);

ALTER TABLE ALLOCATION_CATEGORY_OPTION_LEVEL ADD (SHOW_COPY_OPTION_TO_SEGMENTATION_CHECK_BOX TINYINT DEFAULT 0);

UPDATE ACOL
SET
    ACOL.SHOW_COPY_OPTION_TO_SEGMENTATION_CHECK_BOX = 1
    , ACOL.MODIFIED_DATE_TZ = CURRENT_TIMESTAMP
    , ACOL.MODIFIED_USER_ID = 1
FROM ALLOCATION_CATEGORY_OPTION_LEVEL ACOL
INNER JOIN ALLOCATION_CATEGORY AC
    ON AC.ALLOCATION_CATEGORY_ID = ACOL.ALLOCATION_CATEGORY_ID
    AND UPPER(AC.NAME) = 'INDUSTRIES'
    AND AC.ENABLED = 1
    AND AC.DELETED = 0
WHERE ACOL.HIERARCHY_LEVEL_ID = 2;

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-60', 'Implement Segmientation Form', 'V201709041100__Implement_Segmientation_Form.sql');

COMMIT;