-- IMPORTANT: Remember to excecute the commented code before deleting the HL4 column

--******** DELETE REFERENTIAL CONSTRAINT TO HL4 ********
-- select * from "REFERENTIAL_CONSTRAINTS"
-- where TABLE_NAME = 'INTERLOCK_REQUEST'
-- order by COLUMN_NAME

-- MAKE SURE YOU ARE DELETING THE CONSTRAINT OF MKTG_PLANNING_TOOL
-- *** delete the constraint from the table:
-- ALTER TABLE "INTERLOCK_REQUEST" DROP CONSTRAINT '<CONSTRAINT_NAME>';

ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST" DROP(HL4_ID);

-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-64', 'Remove HL4_ID from INTERLOCK_REQUEST', 'V201709210940_remove_hl4_id_from_interlock_request.sql');

COMMIT;