ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (AFFILIATED_WITH_LARGER_EVENT_ID BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (AFFILIATED_EVENT_NAME NVARCHAR(255));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (EXISTING_CUSTOMER_PERCENTAGE DECIMAL(19,2));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (TARGET_AUDIENCE_ID BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (GROSS_COST DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (NET_COST DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (EXPECTED_REVENUE DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (EXPECTED_COFOUNDING DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (REGISTRATION_PROCESS_ID BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (BUSINESS_CASE NVARCHAR(1000));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (EVENT_FOLLOW_UP_ACTIVITIES NVARCHAR(255));

ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (AFFILIATED_WITH_LARGER_EVENT_ID BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (AFFILIATED_EVENT_NAME NVARCHAR(255));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (EXISTING_CUSTOMER_PERCENTAGE DECIMAL(19,2));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (TARGET_AUDIENCE_ID BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (GROSS_COST DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (NET_COST DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (EXPECTED_REVENUE DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (EXPECTED_COFOUNDING DECIMAL(19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (REGISTRATION_PROCESS_ID BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (BUSINESS_CASE NVARCHAR(1000));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (EVENT_FOLLOW_UP_ACTIVITIES NVARCHAR(255));


-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-183', 'Add Event Planning form new columns for HL5 and HL6', 'V201911190845__Create_HL5_HL6_Event_Planning_Form_columns.sql');

COMMIT;
