create column table "MKTG_PLANNING_TOOL"."HL5_LEGACY_BUDGET"(
	"HL5_LEGACY_BUDGET_ID" bigint not null primary key generated by default as IDENTITY,
	"HL5_LEGACY_ID" BIGINT NOT NULL,
	"ORGANIZATION_ID" BIGINT,
	"PERCENTAGE" DECIMAL(19,2),
	"ORGANIZATION_TYPE" TINYINT NOT NULL,

	"CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
    "MODIFIED_DATE_TZ" timestamp,
    "CREATED_USER_ID" bigint not null,
    "MODIFIED_USER_ID" bigint,
    "ENABLED" tinyint default 1,
    "DELETED" tinyint default 0,

	FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);


-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
     VALUES('V5.0.0-181', 'Add HL5_LEGACY_BUDGET table', 'V201905221630__Create_hl5_legacy_budget_table.sql');

     COMMIT;