INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_TAB" (DYNAMIC_FORM_TAB_ID, TAB_NAME, TAB_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID)
VALUES(26, 'EVENT_PLANNING_FORM', 'Event Planning Form', 2, 85);

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_TAB" (DYNAMIC_FORM_TAB_ID, TAB_NAME, TAB_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID)
VALUES(27, 'EVENT_PLANNING_FORM', 'Event Planning Form', 3, 85);

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('AFFILIATED_WITH_LARGER_EVENT_ID', 'Affiliated With Larger Event', 2, 85, 1, 26, 33, 'select');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('AFFILIATED_EVENT_NAME', 'Name of Affiliated Event (if applicable)', 2, 85, 1, 26, 34, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EXISTING_CUSTOMER_PERCENTAGE', '% of Existing Customer (of the total attendees)', 2, 85, 1, 26, 35, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('TARGET_AUDIENCE_ID', 'Target Audience', 2, 85, 1, 26, 36, 'select');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('GROSS_COST', 'Gross Costs (EUR) (Total cost to host)', 2, 85, 1, 26, 37, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('NET_COST', 'Net Cost (EUR) (Cost from your budget)', 2, 85, 1, 26, 38, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EXPECTED_REVENUE', 'Expected revenue (EUR) (Revenue line of P&L)', 2, 85, 1, 26, 39, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EXPECTED_COFOUNDING', 'Expected Cofunding/Other Offsets (EUR) (Other changes to P&L)', 2, 85, 1, 26, 40, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('REGISTRATION_PROCESS_ID', 'Registration Process', 2, 85, 1, 26, 41, 'select');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('BUSINESS_CASE', 'Business Case', 2, 85, 1, 26, 42, 'textarea');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EVENT_FOLLOW_UP_ACTIVITIES', 'Event Follow-up Activities', 2, 85, 1, 26, 43, 'textarea');

-- HL6
INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('AFFILIATED_WITH_LARGER_EVENT_ID', 'Affiliated With Larger Event', 3, 85, 1, 27, 33, 'select');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('AFFILIATED_EVENT_NAME', 'Name of Affiliated Event (if applicable)', 3, 85, 1, 27, 34, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EXISTING_CUSTOMER_PERCENTAGE', '% of Existing Customer (of the total attendees)', 3, 85, 1, 27, 35, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('TARGET_AUDIENCE_ID', 'Target Audience', 3, 85, 1, 27, 36, 'select');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('GROSS_COST', 'Gross Costs (EUR) (Total cost to host)', 3, 85, 1, 27, 37, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('NET_COST', 'Net Cost (EUR) (Cost from your budget)', 3, 85, 1, 27, 38, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EXPECTED_REVENUE', 'Expected revenue (EUR) (Revenue line of P&L)', 3, 85, 1, 27, 39, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EXPECTED_COFOUNDING', 'Expected Cofunding/Other Offsets (EUR) (Other changes to P&L)', 3, 85, 1, 27, 40, 'text');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('REGISTRATION_PROCESS_ID', 'Registration Process', 3, 85, 1, 27, 41, 'select');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('BUSINESS_CASE', 'Business Case', 3, 85, 1, 27, 42, 'textarea');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EVENT_FOLLOW_UP_ACTIVITIES', 'Event Follow-up Activities', 3, 85, 1, 27, 43, 'textarea');

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-184', 'Add Dynamic Form information about Event Planning Form tab and columns', 'V201911191100__Update_Event_Planning_Form_Dynamic_Form_data.sql');

COMMIT;
