CREATE PROCEDURE "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT" (
	IN IN_TABLE_NAME NVARCHAR(255),
	IN IN_REFERENCED_TABLE_NAME NVARCHAR(255)

)
	LANGUAGE SQLSCRIPT
	SQL SECURITY INVOKER

	AS
BEGIN
   	DECLARE VALUE_CONSTRAINT NVARCHAR(255);
   	VALUE_CONSTRAINT := '';

	SELECT COALESCE(CONSTRAINT_NAME, '') INTO VALUE_CONSTRAINT from "SYS"."REFERENTIAL_CONSTRAINTS"
	WHERE TABLE_NAME = IN_TABLE_NAME AND REFERENCED_TABLE_NAME = IN_REFERENCED_TABLE_NAME
	AND SCHEMA_NAME = 'MKTG_PLANNING_TOOL';

	IF (:VALUE_CONSTRAINT <> '' )
	THEN
	exec 'ALTER TABLE '||:IN_TABLE_NAME||' DROP CONSTRAINT '||:VALUE_CONSTRAINT;
	COMMIT;
	END IF;

END;
--call procedure to delete FK
CALL "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT"('HL5','DISTRIBUTION_CHANNEL');
CALL "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT"('HL6','ROUTE_TO_MARKET');
CALL "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT"('HL6','SALE_ORGANIZATION');

--drop procedure from BD
DROP PROCEDURE "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT" ;
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-109', 'Delete HL5 and HL6 Distribution Channel, Rout to Market and Marketing Organization Constraints', 'V201801031322__Delete_Hl5_Hl6_Constraint.sql');

COMMIT;