INSERT INTO "MKTG_PLANNING_TOOL"."HL4_STATUS_DETAIL" (HL4_STATUS_DETAIL_ID, DETAIL)
VALUES (9, 'Deletion Request');
INSERT INTO "MKTG_PLANNING_TOOL"."HL4_STATUS_DETAIL" (HL4_STATUS_DETAIL_ID, DETAIL)
VALUES (10, 'Deleted In CRM');

INSERT INTO "MKTG_PLANNING_TOOL"."HL5_STATUS_DETAIL" (HL5_STATUS_DETAIL_ID, DETAIL, CREATED_USER_ID)
VALUES (9, 'Deletion Request', 1);
INSERT INTO "MKTG_PLANNING_TOOL"."HL5_STATUS_DETAIL" (HL5_STATUS_DETAIL_ID, DETAIL, CREATED_USER_ID)
VALUES (10, 'Deleted In CRM', 1);

INSERT INTO "MKTG_PLANNING_TOOL"."HL6_STATUS_DETAIL" (HL6_STATUS_DETAIL_ID, DETAIL, CREATED_USER_ID)
VALUES (9, 'Deletion Request', 1);
INSERT INTO "MKTG_PLANNING_TOOL"."HL6_STATUS_DETAIL" (HL6_STATUS_DETAIL_ID, DETAIL, CREATED_USER_ID)
VALUES (10, 'Deleted In CRM', 1);

ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" ADD (DELETION_REASON NVARCHAR(255) NULL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (DELETION_REASON NVARCHAR(255) NULL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (DELETION_REASON NVARCHAR(255) NULL);

--***************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-117', 'Add new status when user deletes a record in In CRM status', 'V201801231200__Add_New_Deletion_Status.sql');

COMMIT;