DELETE FROM "MKTG_PLANNING_TOOL"."UPLOAD_MAP" where DATA_TYPE = 'HL1' AND COLUMN_NAME = 'SUBREGION_ID';

ALTER TABLE "MKTG_PLANNING_TOOL"."HL1" DROP (SUBREGION_ID);


insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('SUBREGION_ID', 'CSV_SUBREGION_ID', 'HL2', '"MKTG_PLANNING_TOOL"."SUBREGION"', 'SUBREGION_ID', 'SUBREGION_NAME', 1, 2);

UPDATE  "MKTG_PLANNING_TOOL"."UPLOAD_MAP"
SET OTHER_CONDITION = 'AND ENABLED = 1 AND DELETED = 0'
WHERE COLUMN_NAME = 'ASSOCIATED_USER'


-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-80', 'Update all object related to Upload', 'V201710261125__Sub_region_Upload.sql');

COMMIT;