ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST" ADD (COMMENTS NVARCHAR(255));

-- Update schema version
INSERT INTO "MKTG_PLANNING_TOOL"."SCHEMA_VERSION"(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-75', 'Add new column COMMENTS to INTERLOCK_REQUEST table', 'V201710191025__Alter_interlock_request_add_comments.sql');

COMMIT;