alter table "MKTG_PLANNING_TOOL"."HL3" add(COST_CENTER nvarchar(10) null);
alter table "MKTG_PLANNING_TOOL"."HL4" add(COST_CENTER nvarchar(10) null);
alter table "MKTG_PLANNING_TOOL"."HL3" add(SHOPPING_CART_APPROVER nvarchar(10) null);
alter table "MKTG_PLANNING_TOOL"."HL4" add(SHOPPING_CART_APPROVER nvarchar(10) null);

alter table "MKTG_PLANNING_TOOL"."COST_CENTER" add(PERSON_RESPONSIBLE nvarchar(10) null);


-- Add new fields to upload dictionary
insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('COST_CENTER', 'CSV_COST_CENTER', 'HL3', '', '', '', 1, 4);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('SHOPPING_CART_APPROVER', 'CSV_SHOPPING_CART_APPROVER', 'HL3', '', '', '', 1, 4);

-- Update schema version
INSERT INTO "MKTG_PLANNING_TOOL"."SCHEMA_VERSION"(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-72', 'Add new fields to l3 and l4', 'V201710131058_Shopping_cart_approver_and_cost_center_l3_l4.sql');

COMMIT;