--Add region EMEA_S
INSERT INTO REGION (REGION_NAME, REGION_ISO, TIME_ZONE_OFFSET, START_TIME, END_TIME, IS_GLOBAL_REGION, CREATED_USER_ID)
VALUES ('EMEA_S', 'EMEA_S', ' UTC +1', 80000, 160000, 1, 1);

--Add region EMEA_N
INSERT INTO REGION (REGION_NAME, REGION_ISO, TIME_ZONE_OFFSET, START_TIME, END_TIME, IS_GLOBAL_REGION, CREATED_USER_ID)
VALUES ('EMEA_N', 'EMEA_N', ' UTC +1', 80000, 160000, 1, 1);

--Add region MEE
INSERT INTO REGION (REGION_NAME, REGION_ISO, TIME_ZONE_OFFSET, START_TIME, END_TIME, IS_GLOBAL_REGION, CREATED_USER_ID)
VALUES ('MEE', 'MEE', ' UTC +1', 80000, 160000, 1, 1);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-172', 'Add new regions', 'V2018112214300__Add_new_regions.sql');

COMMIT;