

DELETE FROM UPLOAD_MAP
WHERE COLUMN_NAME = 'EMPLOYEE_RESPONSIBLE_ID' AND (TYPE = 0 OR TYPE = 1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
VALUES(0, 'EMPLOYEE_RESPONSIBLE_ID', 'Employee Responsible', 'STRING',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
VALUES(1, 'EMPLOYEE_RESPONSIBLE_ID', 'Employee Responsible', 'STRING',1);

DELETE FROM UPLOAD_MAP
WHERE CSV_COLUMN_NAME = 'Marketing Organisation Description';

DELETE FROM UPLOAD_MAP
WHERE COLUMN_NAME = 'SALES_ORGANIZATION_ID' AND (TYPE = 0 OR TYPE = 1);

INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
VALUES(0, 'SALES_ORGANIZATION_ID', 'Marketing Organization', 'STRING',
'"MKTG_PLANNING_TOOL"."SALE_ORGANIZATION"','SALES_ORGANIZATION_ID','CRM_KEY',1);

INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
 FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
 VALUES(1, 'SALES_ORGANIZATION_ID', 'Marketing Organization', 'STRING',
 '"MKTG_PLANNING_TOOL"."SALE_ORGANIZATION"','SALES_ORGANIZATION_ID','CRM_KEY',1);

DELETE FROM UPLOAD_MAP WHERE CSV_COLUMN_NAME = 'Marketing Organisation Description';


UPDATE UPLOAD_MAP
SET DATA_TYPE = 'KPI'
WHERE (COLUMN_NAME = 'EXPECTED_OUTCOME_OPTION_ID'
)
AND
DATA_TYPE <> 'KPI'
AND
(TYPE = 0 OR TYPE = 1);



UPDATE UPLOAD_MAP
SET FOREIGN_COLUMN_FILTER = 'CRM_KEY'
WHERE (COLUMN_NAME = 'CAMPAIGN_TYPE_ID'
OR COLUMN_NAME = 'CAMPAIGN_SUBTYPE_ID'
OR COLUMN_NAME = 'CAMPAIGN_OBJECTIVE_ID'
OR COLUMN_NAME = 'PRIORITY_ID'
OR COLUMN_NAME = 'DISTRIBUTION_CHANNEL_ID'
OR COLUMN_NAME = 'ROUTE_TO_MARKET_ID'
)
AND
(TYPE = 0 OR TYPE = 1);

INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0, 'TOP_NODE', 'Top Node', 'STRING',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1, 'TOP_NODE', 'Top Node', 'STRING',1);

INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIMP_PERCENTAGE1', 'ZZIMP_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIMP_PERCENTAGE2', 'ZZIMP_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIMP_PERCENTAGE3', 'ZZIMP_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIMP_PERCENTAGE4', 'ZZIMP_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIMP_PERCENTAGE5', 'ZZIMP_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIND_PERCENTAGE1', 'ZZIND_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIND_PERCENTAGE2', 'ZZIND_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIND_PERCENTAGE3', 'ZZIND_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIND_PERCENTAGE4', 'ZZIND_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZIND_PERCENTAGE5', 'ZZIND_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZMSEG_PERCENTAGE1', 'ZZMSEG_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZMSEG_PERCENTAGE2', 'ZZMSEG_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZMSEG_PERCENTAGE3', 'ZZMSEG_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZMSEG_PERCENTAGE4', 'ZZMSEG_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZMSEG_PERCENTAGE5', 'ZZMSEG_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZSOL_PERCENTAGE1', 'ZZSOL_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZSOL_PERCENTAGE2', 'ZZSOL_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZSOL_PERCENTAGE3', 'ZZSOL_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZSOL_PERCENTAGE4', 'ZZSOL_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(0,'ZZSOL_PERCENTAGE5', 'ZZSOL_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE,  FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'IMP1', 'IMP1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE,  FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'IMP2', 'IMP2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'IMP3', 'IMP3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'IMP4', 'IMP4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'IMP5', 'IMP5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'INDUSTRY1', 'INDUSTRY1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'INDUSTRY2', 'INDUSTRY2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'INDUSTRY3', 'INDUSTRY3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'INDUSTRY4', 'INDUSTRY4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'INDUSTRY5', 'INDUSTRY5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'MKTSEG1', 'MKTSEG1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'MKTSEG2', 'MKTSEG2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'MKTSEG3', 'MKTSEG3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'MKTSEG4', 'MKTSEG4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'MKTSEG5', 'MKTSEG5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'SOLUTION1', 'SOLUTION1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'SOLUTION2', 'SOLUTION2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'SOLUTION3', 'SOLUTION3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'SOLUTION4', 'SOLUTION4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(0,'SOLUTION5', 'SOLUTION5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);

INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIMP_PERCENTAGE1', 'ZZIMP_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIMP_PERCENTAGE2', 'ZZIMP_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIMP_PERCENTAGE3', 'ZZIMP_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIMP_PERCENTAGE4', 'ZZIMP_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIMP_PERCENTAGE5', 'ZZIMP_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIND_PERCENTAGE1', 'ZZIND_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIND_PERCENTAGE2', 'ZZIND_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIND_PERCENTAGE3', 'ZZIND_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIND_PERCENTAGE4', 'ZZIND_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZIND_PERCENTAGE5', 'ZZIND_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZMSEG_PERCENTAGE1', 'ZZMSEG_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZMSEG_PERCENTAGE2', 'ZZMSEG_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZMSEG_PERCENTAGE3', 'ZZMSEG_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZMSEG_PERCENTAGE4', 'ZZMSEG_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZMSEG_PERCENTAGE5', 'ZZMSEG_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZSOL_PERCENTAGE1', 'ZZSOL_PERCENTAGE1', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZSOL_PERCENTAGE2', 'ZZSOL_PERCENTAGE2', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZSOL_PERCENTAGE3', 'ZZSOL_PERCENTAGE3', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZSOL_PERCENTAGE4', 'ZZSOL_PERCENTAGE4', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, CREATED_USER_ID)
     VALUES(1,'ZZSOL_PERCENTAGE5', 'ZZSOL_PERCENTAGE5', 'PER',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'IMP1', 'IMP1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'IMP2', 'IMP2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'IMP3', 'IMP3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'IMP4', 'IMP4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'IMP5', 'IMP5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'INDUSTRY1', 'INDUSTRY1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'INDUSTRY2', 'INDUSTRY2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'INDUSTRY3', 'INDUSTRY3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'INDUSTRY4', 'INDUSTRY4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'INDUSTRY5', 'INDUSTRY5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'MKTSEG1', 'MKTSEG1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'MKTSEG2', 'MKTSEG2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'MKTSEG3', 'MKTSEG3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'MKTSEG4', 'MKTSEG4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'MKTSEG5', 'MKTSEG5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'SOLUTION1', 'SOLUTION1', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'SOLUTION2', 'SOLUTION2', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'SOLUTION3', 'SOLUTION3', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'SOLUTION4', 'SOLUTION4', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);
INSERT INTO UPLOAD_MAP(TYPE, COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME,
FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID)
     VALUES(1,'SOLUTION5', 'SOLUTION5', 'OPTION','"MKTG_PLANNING_TOOL"."ALLOCATION_OPTION"', 'ALLOCATION_OPTION_ID', 'CRM_KEY',1);



--***************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-114', 'Contain all changes to update the upload for l5 and L6', 'V201801101600__UPLDATE_UPLOAD_L5_L6.sql');

COMMIT;