ALTER TABLE "MKTG_PLANNING_TOOL"."BUDGET_YEAR" ADD (ENABLE_CRM_CREATION TINYINT DEFAULT 0);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" ADD (ENABLE_CRM_CREATION TINYINT DEFAULT 0);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD (ENABLE_CRM_CREATION TINYINT DEFAULT 0);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD (ENABLE_CRM_CREATION TINYINT DEFAULT 0);


-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-162', 'Create a column named ENABLE_CRM_CREATION with default 0 in HL4-6 and Budget Year', 'V201806121118_Budget_Year_Enable_CRM_Creation.sql');

COMMIT;