
CREATE PROCEDURE "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT" (

	IN IN_TABLE_NAME NVARCHAR(255),
	IN IN_REFERENCED_TABLE_NAME NVARCHAR(255)

)
	LANGUAGE SQLSCRIPT
	SQL SECURITY INVOKER

	AS
BEGIN
   	DECLARE VALUE_CONSTRAINT NVARCHAR(255);
   	VALUE_CONSTRAINT := '';

	SELECT COALESCE(CONSTRAINT_NAME, '') INTO VALUE_CONSTRAINT from "SYS"."REFERENTIAL_CONSTRAINTS"
	WHERE TABLE_NAME = IN_TABLE_NAME AND REFERENCED_TABLE_NAME = IN_REFERENCED_TABLE_NAME;

	IF (:VALUE_CONSTRAINT <> '' )
	THEN
	exec 'ALTER TABLE '||:IN_TABLE_NAME||' DROP CONSTRAINT '||:VALUE_CONSTRAINT;
	COMMIT;
	END IF;

END;

CALL "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT"('HL5','EURO_CONVERSIONS');
CALL "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT"('HL6','EURO_CONVERSIONS');

DROP PROCEDURE "MKTG_PLANNING_TOOL"."mktgplanningtool.db.procedures::DELETE_CONSTRAINT" ;

--3 rename table "EURO_CONVERSIONS" TO "CURRENCY"
RENAME TABLE "EURO_CONVERSIONS" TO "CURRENCY";

--4 - add a column to the table "EURO_CONVERSION" called "budget_year_id" bigint nulable
ALTER TABLE "MKTG_PLANNING_TOOL"."CURRENCY" ADD ("BUDGET_YEAR_ID" bigint null);

--5 - set default budget_year_id to euro conversion table
UPDATE "MKTG_PLANNING_TOOL"."CURRENCY"
SET BUDGET_YEAR_ID = (SELECT BUDGET_YEAR_ID FROM BUDGET_YEAR
WHERE DEFAULT_YEAR = 1);

--6- assign the value of the default euro_conversion_id to the new column
ALTER TABLE "MKTG_PLANNING_TOOL"."CURRENCY" ALTER (BUDGET_YEAR_ID bigint NOT NULL);

--7 add an FK from "EURO_CONVERSION" to table "BUDGET_YEAR" (reference to new column "budget_year_id")
ALTER TABLE "MKTG_PLANNING_TOOL"."CURRENCY" ADD FOREIGN KEY ("BUDGET_YEAR_ID") REFERENCES "MKTG_PLANNING_TOOL"."BUDGET_YEAR"("BUDGET_YEAR_ID");

--8 adding fk to l5 table to CURRENCY primary key EURO_CONVERSION_ID
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ADD FOREIGN KEY ("EURO_CONVERSION_ID") REFERENCES "MKTG_PLANNING_TOOL"."CURRENCY"("EURO_CONVERSION_ID");

--9 adding fk to l6 table to CURRENCY primary key EURO_CONVERSION_ID
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ADD FOREIGN KEY ("EURO_CONVERSION_ID") REFERENCES "MKTG_PLANNING_TOOL"."CURRENCY"("EURO_CONVERSION_ID");

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-16', 'Rename EURO_CONVERSION to CURRENCY table. Add new BUDGET_YEAR_ID column to currency table', 'V201702011500_EuroConversion_To_Currency.sql');

COMMIT;
