INSERT INTO "MKTG_PLANNING_TOOL"."HIERARCHY_LEVEL" (description, created_user_id) VALUES ('HL2', 1);

create column table "MKTG_PLANNING_TOOL"."HL2_EXPECTED_OUTCOMES" (
        "HL2_EXPECTED_OUTCOMES_ID" bigint not null primary key generated by default as IDENTITY,
        "HL2_ID" bigint NOT NULL,
        "COMMENTS" NVARCHAR(3000) NULL,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("HL2_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL2"("HL2_ID")
);

create column table "MKTG_PLANNING_TOOL"."HL2_EXPECTED_OUTCOMES_DETAIL" (
        "HL2_EXPECTED_OUTCOMES_DETAILS_ID" bigint not null primary key generated by default as IDENTITY,
        "HL2_EXPECTED_OUTCOMES_ID" bigint NOT NULL,
        "EXPECTED_OUTCOME_LEVEL_ID" bigint NOT NULL,
        "EURO_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "VOLUME_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("EXPECTED_OUTCOME_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL"("EXPECTED_OUTCOME_LEVEL_ID"),
        FOREIGN KEY ("HL2_EXPECTED_OUTCOMES_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL2_EXPECTED_OUTCOMES"("HL2_EXPECTED_OUTCOMES_ID")
);

create column table "MKTG_PLANNING_TOOL"."HL3_EXPECTED_OUTCOMES" (
        "HL3_EXPECTED_OUTCOMES_ID" bigint not null primary key generated by default as IDENTITY,
        "HL3_ID" bigint NOT NULL,
        "COMMENTS" NVARCHAR(3000) NULL,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("HL3_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL3"("HL3_ID")
);

create column table "MKTG_PLANNING_TOOL"."HL3_EXPECTED_OUTCOMES_DETAIL" (
        "HL3_EXPECTED_OUTCOMES_DETAILS_ID" bigint not null primary key generated by default as IDENTITY,
        "HL3_EXPECTED_OUTCOMES_ID" bigint NOT NULL,
        "EXPECTED_OUTCOME_LEVEL_ID" bigint NOT NULL,
        "EURO_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "VOLUME_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("EXPECTED_OUTCOME_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL"("EXPECTED_OUTCOME_LEVEL_ID"),
        FOREIGN KEY ("HL3_EXPECTED_OUTCOMES_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL3_EXPECTED_OUTCOMES"("HL3_EXPECTED_OUTCOMES_ID")
);

-- L2 KPIs --
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 1, 5, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 2, 5, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 3, 5, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 4, 5, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 5, 5, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 6, 5, 1);


-- L3 KPIs --
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 1, 4, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 2, 4, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 3, 4, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 4, 4, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 5, 4, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 6, 4, 1);
-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V5.0.0-54', 'Add L2 L2 KPIs tab', 'V201708141330__Add_L2_L2_kpis_tab.sql');

COMMIT;