ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" ALTER (BUDGET DECIMAL(19,6) NOT NULL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5" ALTER (BUDGET DECIMAL(19,6) NOT NULL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6" ALTER (BUDGET DECIMAL(19,6) NOT NULL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5_LEGACY" ALTER (BUDGET DECIMAL(19,6) NOT NULL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4_IN_CRM_VERSION" ALTER (HL4_FNC_BUDGET_TOTAL_MKT DECIMAL (19,6));
ALTER TABLE "MKTG_PLANNING_TOOL"."HL5_IN_CRM_VERSION" ALTER (BUDGET DECIMAL(19,6) NOT NULL);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL6_IN_CRM_VERSION" ALTER (BUDGET DECIMAL(19,6) NOT NULL);


-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-161', 'Set precision in Budget columns to 19,6', 'V201806071638__Budget_Column_Set_Precision_19_6.sql');

COMMIT;