DELETE FROM "MKTG_PLANNING_TOOL"."UPLOAD_MAP" WHERE DATA_TYPE = 'HL1';

----------****HL1*****------

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ACRONYM', 'CSV_ACRONYM', 'HL1', '', '', '', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('DESCRIPTION', 'CSV_DESCRIPTION', 'HL1', '', '', '', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('BUDGET', 'CSV_BUDGET', 'HL1', '', '', '', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('REGION_ID', 'CSV_REGION_ID', 'HL1', '"MKTG_PLANNING_TOOL"."REGION"', 'REGION_ID', 'REGION_NAME', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('SUBREGION_ID', 'CSV_SUBREGION_ID', 'HL1', '"MKTG_PLANNING_TOOL"."SUBREGION"', 'SUBREGION_ID', 'SUBREGION_NAME', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('CRT_RELATED', 'CSV_CRT_RELATED', 'HL1', '', '', '', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('IMPLEMENT_EXECUTION_LEVEL', 'CSV_IMPLEMENT_EXECUTION_LEVEL', 'HL1', '', '', '', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('TEAM_TYPE_ID', 'CSV_TEAM_TYPE_ID', 'HL1', '', '', '', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ASSOCIATED_USER', 'CSV_ASSOCIATED_USER', 'HL1', '"MKTG_PLANNING_TOOL"."USER"', 'USER_ID', 'USER_NAME', 1, 2);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('BUDGET_YEAR_ID', 'CSV_BUDGET_YEAR_ID', 'HL1', '"MKTG_PLANNING_TOOL"."BUDGET_YEAR"', 'BUDGET_YEAR_ID', 'BUDGET_YEAR', 1, 2);

----------****HL2*****------
insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ORGANIZATION_ACRONYM', 'CSV_ACRONYM', 'HL2', '', '', '', 1, 3);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ORGANIZATION_NAME', 'CSV_DESCRIPTION', 'HL2', '', '', '', 1, 3);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('HL2_BUDGET_TOTAL', 'CSV_BUDGET', 'HL2', '', '', '', 1, 3);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('IMPLEMENT_EXECUTION_LEVEL', 'CSV_IMPLEMENT_EXECUTION_LEVEL', 'HL2', '', '', '', 1, 3);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('CRT_RELATED', 'CSV_CRT_RELATED', 'HL2', '', '', '', 1, 3);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ASSOCIATED_USER', 'CSV_ASSOCIATED_USER', 'HL2', '"MKTG_PLANNING_TOOL"."USER"', 'USER_ID', 'USER_NAME', 1, 3);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ALLOW_AUTOMATIC_BUDGET_APPROVAL', 'CSV_AUTOMATIC_BUDGET_APPROVAL', 'HL2', '', '', '', 1, 3);

----------****HL3*****------
insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ACRONYM', 'CSV_ACRONYM', 'HL3', '', '', '', 1, 4);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('HL3_DESCRIPTION', 'CSV_DESCRIPTION', 'HL3', '', '', '', 1, 4);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('HL3_FNC_BUDGET_TOTAL', 'CSV_BUDGET', 'HL3', '', '', '', 1, 4);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER, CREATED_USER_ID, TYPE)
values ('ASSOCIATED_USER', 'CSV_ASSOCIATED_USER', 'HL3', '"MKTG_PLANNING_TOOL"."USER"', 'USER_ID', 'USER_NAME', 1, 4);

insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER,CREATED_USER_ID, TYPE)
values ( 'EXPECTED_OUTCOME_NAME', 'CSV_TARGET_TYPE', 'KPI', '"MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME"' , 'EXPECTED_OUTCOME_ID', 'NAME', 1, 0);
insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER,CREATED_USER_ID, TYPE)
values ( 'EXPECTED_OUTCOME_OPTION_NAME', 'CSV_OPTION', 'KPI', '"MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION"' , 'EXPECTED_OUTCOME_OPTION_ID', 'NAME', 1, 0);
insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER,CREATED_USER_ID, TYPE)
values ( 'EXPECTED_OUTCOME_OPTION_VOLUME', 'CSV_VOLUME', 'KPI', '' , '', '', 1, 0);
insert into "MKTG_PLANNING_TOOL"."UPLOAD_MAP"( COLUMN_NAME, CSV_COLUMN_NAME, DATA_TYPE, FOREIGN_TABLE_NAME, FOREIGN_COLUMN_REFERENCE, FOREIGN_COLUMN_FILTER,CREATED_USER_ID, TYPE)
values ( 'EXPECTED_OUTCOME_OPTION_VALUE', 'CSV_VALUE', 'KPI', '' , '', '', 1, 0);

--- field and table to support Import
ALTER TABLE "MKTG_PLANNING_TOOL"."HL1" ADD ("IMPORTED" TINYINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL2" ADD ("IMPORTED" TINYINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL3" ADD ("IMPORTED" TINYINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL2" ADD ("IMPORT_ID" BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL3" ADD ("IMPORT_ID" BIGINT);

ALTER TABLE HL1 ADD CONSTRAINT IMPORT_HL1 FOREIGN KEY (import_id) REFERENCES IMPORT_HL(import_id);
ALTER TABLE HL2 ADD CONSTRAINT IMPORT_HL2 FOREIGN KEY (import_id) REFERENCES IMPORT_HL(import_id);
ALTER TABLE HL3 ADD CONSTRAINT IMPORT_HL3 FOREIGN KEY (import_id) REFERENCES IMPORT_HL(import_id);

insert into "MKTG_PLANNING_TOOL"."RESOURCE" (NAME,CREATED_USER_ID,OBJECT_NAME) values('Upload',1,'upload');
insert into "MKTG_PLANNING_TOOL"."ROLE_PERMISSION"(ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID) values(1,15,10,1);--you must check ir the Resourse_id is 15.

create column table "MKTG_PLANNING_TOOL"."IMPORT_HL" (
	import_id bigint not null primary key generated by default as IDENTITY,
	description nvarchar(255),
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "MKTG_PLANNING_TOOL".USER(user_id)
);

-----------------------------------------
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-55', 'Include changes to Import Hl1 and Hl2 and Hl3', 'V201708141700__Import_HL1HL2HL3.sql');

COMMIT;