DELETE FROM "MKTG_PLANNING_TOOL"."LOG_INTERLOCK_REQUEST_STATUS";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST";

DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_CONTACT_DATA";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_ROUTE";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_MESSAGE";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_REGION";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_SUBREGION";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_CENTRAL_REGION_CONTACT_DATA";
DELETE FROM "MKTG_PLANNING_TOOL"."ORGANIZATION_TYPE_INTERLOCK_ORGANIZATION";

--***** IMPORTANT: Remember to excecute the commented code before proceding with the rest of the script *****

-- select * from "REFERENTIAL_CONSTRAINTS"
-- where TABLE_NAME = 'INTERLOCK_REQUEST_ROUTE'
-- order by COLUMN_NAME

-- ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_ROUTE" DROP CONSTRAINT <CONSTRAINT_NAME>;

-- Rename column name to INTERLOCK_ORGANIZATION_ID
RENAME COLUMN "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_ROUTE".ROUTE_ID to INTERLOCK_ORGANIZATION_ID;
-- Add foreign key to INTERLOCK_ORGANIZATION_TABLE
ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_ROUTE" ADD FOREIGN KEY ( "INTERLOCK_ORGANIZATION_ID" ) REFERENCES "MKTG_PLANNING_TOOL"."INTERLOCK_ORGANIZATION" ("INTERLOCK_ORGANIZATION_ID") ON UPDATE RESTRICT ON DELETE RESTRICT;

-- Rename Table to be consistent with the new relation
RENAME TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_ROUTE" TO "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_INTERLOCK_ORGANIZATION";

-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-68', 'Clear Interlock - replace INTERLOCK_REQUEST_ROUTE with INTERLOCK_REQUEST_INTERLOCK_ORGANIZATION', 'V201709261455_clear_create_interlock_request_interlock_organization.sql');

COMMIT;