
-- *************************************************************************************
-- Insert deltaTimeLastUpdate to CONFIGURATION table
INSERT INTO "MKTG_PLANNING_TOOL"."CONFIGURATION"(KEY, VALUE, DESCRIPTION, created_user_id) VALUES ('deltaTimeLastUpdate', 12, 'Default hours since the last update for Report Data Export API', 1);

-- *************************************************************************************
-- Add EXPORT_KEY column and set values
ALTER TABLE "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION" ADD (EXPORT_KEY NVARCHAR(25));

UPDATE "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION"
SET EXPORT_KEY = 'MNP'
WHERE NAME = 'MNP';

UPDATE "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION"
SET EXPORT_KEY = 'MTP'
WHERE NAME = 'MTP';

UPDATE "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION"
SET EXPORT_KEY = 'MIP'
WHERE NAME = 'MIP';

UPDATE "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION"
SET EXPORT_KEY = 'LEAD_VOLUMN'
WHERE NAME = 'Lead Volume';

-- *************************************************************************************
-- Create table LOG_REPORT_EXPORT_DATA
CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."LOG_REPORT_EXPORT_DATA" (
	"LOG_REPORT_EXPORT_DATA_ID" bigint not null primary key generated by default as IDENTITY,
	"MODE" INTEGER NOT NULL,
	"FILTER_CRITERIA" NVARCHAR(255),
	"CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP
 );

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-108', 'Added EXPORT_KEY column to EXPECTED_OUTCOME_OPTION, added a default time in hours to configuration for API', 'V201712211510__Add_export_key_to_Expected_Outcome_Option_insert_delta_time_into_Configuration.sql');

COMMIT;