UPDATE "MKTG_PLANNING_TOOL"."HL4"
SET HL4_CRM_DESCRIPTION =  SUBSTRING(HL4_CRM_DESCRIPTION, 0, 40);

UPDATE "MKTG_PLANNING_TOOL"."HL5"
SET HL5_CRM_DESCRIPTION =  SUBSTRING(HL5_CRM_DESCRIPTION, 0, 40);

UPDATE "MKTG_PLANNING_TOOL"."HL6"
SET HL6_CRM_DESCRIPTION =  SUBSTRING(HL6_CRM_DESCRIPTION, 0, 40);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-107', 'Update Crm_Description Field for L4, L5 and L6', 'V201712201745__Update_Crm_Description_Field_L4_L5_L6.sql');

COMMIT;