CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL1_CATEGORY_OPTION" (
        HL1_CATEGORY_OPTION_ID bigint not null primary key generated by default as IDENTITY,
        ALLOCATION_CATEGORY_OPTION_LEVEL_ID BIGINT NOT NULL,
        AMOUNT DECIMAL(19,2) NOT NULL,
        HL1_ID BIGINT NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        updated tinyint default 0,
        FOREIGN KEY ("ALLOCATION_CATEGORY_OPTION_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"("ALLOCATION_CATEGORY_OPTION_LEVEL_ID"),
        FOREIGN KEY ("HL1_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL1"("HL1_ID"),
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL3_CATEGORY_OPTION" (
        HL3_CATEGORY_OPTION_ID bigint not null primary key generated by default as IDENTITY,
        ALLOCATION_CATEGORY_OPTION_LEVEL_ID BIGINT NOT NULL,
        AMOUNT DECIMAL(19,2) NOT NULL,
        HL3_ID BIGINT NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        updated tinyint default 0,
        FOREIGN KEY ("ALLOCATION_CATEGORY_OPTION_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"("ALLOCATION_CATEGORY_OPTION_LEVEL_ID"),
        FOREIGN KEY ("HL3_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL3"("HL3_ID"),
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);

insert into "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"(ALLOCATION_CATEGORY_ID,
 ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, IN_PROCESSING_REPORT, CREATED_USER_ID)
 (select acol.ALLOCATION_CATEGORY_ID, acol.ALLOCATION_OPTION_ID, 6 as HIERARCHY_LEVEL_ID, acol.IN_PROCESSING_REPORT, acol.CREATED_USER_ID
 from ALLOCATION_CATEGORY_OPTION_LEVEL acol where acol.hierarchy_level_id = 5
 and acol.deleted = 0 and acol.enabled = 1);

insert into "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"(ALLOCATION_CATEGORY_ID,
 ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, IN_PROCESSING_REPORT, CREATED_USER_ID)
 (select acol.ALLOCATION_CATEGORY_ID, acol.ALLOCATION_OPTION_ID, 4 as HIERARCHY_LEVEL_ID, acol.IN_PROCESSING_REPORT, acol.CREATED_USER_ID
 from ALLOCATION_CATEGORY_OPTION_LEVEL acol where acol.hierarchy_level_id = 5
 and acol.deleted = 0 and acol.enabled = 1);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-65', 'Change implementation for budget distribution on Marketing Plans L1-L3', 'V201709211040__Change_Implementation_For_Budget_Distribution_On_Marketing_Plans_L1_L3.sql');

COMMIT;