ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" ADD (MKT_ORG_ID BIGINT);
ALTER TABLE "MKTG_PLANNING_TOOL"."HL4" ADD (DIS_CHANNEL_ID BIGINT);

-- Update schema version
INSERT INTO "MKTG_PLANNING_TOOL"."SCHEMA_VERSION"(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-74', 'Add new columns MKT_ORG_ID and DIS_CHANNEL_ID to HL4 table', 'V20171018 _Alter_hl4_add_mkt_org_id_dis_channel_id.sql');

COMMIT;