ALTER TABLE REGION ADD (IS_GLOBAL_REGION TINYINT NOT NULL DEFAULT 0);

INSERT INTO REGION (REGION_NAME, REGION_ISO, TIME_ZONE_OFFSET, START_TIME, END_TIME, IS_GLOBAL_REGION, CREATED_USER_ID)
VALUES ('GLOBAL', 'GLOBAL', 'UTC-4', 140000, 230000, 1, 1);

UPDATE HL1 SET
REGION_ID = (SELECT REGION_ID FROM REGION WHERE IS_GLOBAL_REGION = 1)
WHERE HL1.TEAM_TYPE_ID = 2;

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-97', 'Add global region', 'V201712111202__Add_Global_Region.sql');

COMMIT;