ALTER TABLE OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE ADD ("ACRONYM_HEADER" NVARCHAR(2));

--******************this is just for testing**********************
UPDATE OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE
SET ACRONYM_HEADER = 'AA'
WHERE OBJECTIVE_ID = 1;


UPDATE OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE
SET ACRONYM_HEADER = 'BB'
WHERE OBJECTIVE_ID = 2;


UPDATE OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE
SET ACRONYM_HEADER = 'CC'
WHERE OBJECTIVE_ID = 3;


UPDATE OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE
SET ACRONYM_HEADER = 'DD'
WHERE OBJECTIVE_ID = 4;


UPDATE OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE
SET ACRONYM_HEADER = 'EE'
WHERE OBJECTIVE_ID = 5;

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-49', 'Service Request Category Options', 'V201708081530__CRM_ID_HL5.sql');

COMMIT;