DELETE FROM HL4_CRM_BINDING
WHERE HL4_ID IN
(SELECT HL4_ID FROM HL4
WHERE HL4_STATUS_DETAIL_ID = 2
AND ENABLED = 1 AND DELETED = 0);

UPDATE HL4 SET
HL4_STATUS_DETAIL_ID = 1
WHERE HL4_STATUS_DETAIL_ID = 2
AND ENABLED = 1 AND DELETED = 0;

DELETE FROM HL5_CRM_BINDING
WHERE HL5_ID IN
(SELECT HL5_ID FROM HL5
WHERE HL5_STATUS_DETAIL_ID = 2
AND ENABLED = 1 AND DELETED = 0);

UPDATE HL5 SET
HL5_STATUS_DETAIL_ID = 1
WHERE HL5_STATUS_DETAIL_ID = 2
AND ENABLED = 1 AND DELETED = 0;

DELETE FROM HL6_CRM_BINDING
WHERE HL6_ID IN
(SELECT HL6_ID FROM HL6
WHERE HL6_STATUS_DETAIL_ID = 2
AND ENABLED = 1 AND DELETED = 0);

UPDATE HL6 SET
HL6_STATUS_DETAIL_ID = 1
WHERE HL6_STATUS_DETAIL_ID = 2
AND ENABLED = 1 AND DELETED = 0;

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-104', 'Fix status flow', 'V201712191400__Fix_Status_Flow.sql');

COMMIT;