INSERT INTO "MKTG_PLANNING_TOOL"."HIERARCHY_LEVEL" (description, created_user_id) VALUES ('HL1', 1);


create column table "MKTG_PLANNING_TOOL"."HL1_EXPECTED_OUTCOMES" (
        "HL1_EXPECTED_OUTCOMES_ID" bigint not null primary key generated by default as IDENTITY,
        "HL1_ID" bigint NOT NULL,
        "COMMENTS" NVARCHAR(3000) NULL,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("HL1_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL1"("HL1_ID")
);

create column table "MKTG_PLANNING_TOOL"."HL1_EXPECTED_OUTCOMES_DETAIL" (
        "HL1_EXPECTED_OUTCOMES_DETAILS_ID" bigint not null primary key generated by default as IDENTITY,
        "HL1_EXPECTED_OUTCOMES_ID" bigint NOT NULL,
        "EXPECTED_OUTCOME_LEVEL_ID" bigint NOT NULL,
        "EURO_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "VOLUME_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("EXPECTED_OUTCOME_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL"("EXPECTED_OUTCOME_LEVEL_ID"),
        FOREIGN KEY ("HL1_EXPECTED_OUTCOMES_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL1_EXPECTED_OUTCOMES"("HL1_EXPECTED_OUTCOMES_ID")
);

-- L1 KPIs --
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 1, 6, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 2, 6, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 3, 6, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 4, 6, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 5, 6, 1);
insert into "MKTG_PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL" (expected_outcome_id, expected_outcome_option_id, hierarchy_level_id, created_user_id) VALUES (3, 6, 6, 1);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-61', 'Extend KPIs', 'V201709121235__Extend_KPIs.sql');

COMMIT;