UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'percentage'
WHERE DYNAMIC_FORM_FIELD_ID = 101;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 103;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 104;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 105;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 106;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'percentage'
WHERE DYNAMIC_FORM_FIELD_ID = 112;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 114;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 115;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 116;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET FIELD_TYPE = 'budget'
WHERE DYNAMIC_FORM_FIELD_ID = 117;


-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-185', 'Changed Dynamic Form Field types for columns related with Event Planning Form budgets and percentages', 'V201911211445__Update_Dynamic_Field_Types_for_Event_Planning_Form.sql');

COMMIT;
