/*
------- IMPORTANT: make sure to use this script to delete the generated Constraints before executing the rest of the script -------

select * from "REFERENTIAL_CONSTRAINTS"
where TABLE_NAME = 'INTERLOCK_REQUEST'
order by COLUMN_NAME

ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST" DROP CONSTRAINT _SYS_CONSTRAINT_784457_#20_#F0; --FOR ORGANIZATION_TYPE_ID, replace the constraint name with the correct one
ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST" DROP CONSTRAINT _SYS_CONSTRAINT_784457_#65_#F0; --FOR ORGANIZATION_TYPE_FROM_ID, replace the constraint name with the correct one

*/
-- IMPORTANT: make sure you don't need the current information or make a backup before deleting the tables

DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_CONTACT_DATA";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_INTERLOCK_ORGANIZATION";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_MESSAGE";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_REGION";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_SUBREGION";
DELETE FROM "MKTG_PLANNING_TOOL"."LOG_INTERLOCK_REQUEST_STATUS";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST";

-- Drop deprecated columns
ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST" DROP (ORGANIZATION_TYPE_ID);
ALTER TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST" DROP (ORGANIZATION_TYPE_FROM_ID);

-- Restart Organization Types - Init Interlock default Configuration
DELETE FROM "MKTG_PLANNING_TOOL"."ORGANIZATION_TYPE_INTERLOCK_ORGANIZATION";
DELETE FROM "MKTG_PLANNING_TOOL"."INTERLOCK_DEFAULT_CONFIGURATION";
DELETE FROM "MKTG_PLANNING_TOOL"."ORGANIZATION_TYPE";

INSERT INTO "MKTG_PLANNING_TOOL"."ORGANIZATION_TYPE" (	ORGANIZATION_TYPE_ID, NAME,	ORGANIZATION_RELATED_ID, CREATED_USER_ID)
 	VALUES (1, 'Central Teams',	1, 1);

INSERT INTO "MKTG_PLANNING_TOOL"."ORGANIZATION_TYPE" (	ORGANIZATION_TYPE_ID, NAME,	ORGANIZATION_RELATED_ID, CREATED_USER_ID)
 	VALUES (2, 'Regions', 2, 1);

INSERT INTO "MKTG_PLANNING_TOOL"."ORGANIZATION_TYPE" (	ORGANIZATION_TYPE_ID, NAME,	ORGANIZATION_RELATED_ID, CREATED_USER_ID)
 	VALUES (3, 'Market Unit', 3, 1);

INSERT INTO "MKTG_PLANNING_TOOL"."INTERLOCK_DEFAULT_CONFIGURATION" (INTERLOCK_DEFAULT_CONFIGURATION_ID, ENTITY_ID_FROM, ENTITY_ID_TO, ORGANIZATION_TYPE_FROM, ORGANIZATION_TYPE_TO, INTERLOCK_TYPE_ID, CREATED_USER_ID)
	VALUES(1,1,1,1,1,1,1);

INSERT INTO "MKTG_PLANNING_TOOL"."INTERLOCK_DEFAULT_CONFIGURATION" (INTERLOCK_DEFAULT_CONFIGURATION_ID, ENTITY_ID_FROM, ENTITY_ID_TO, ORGANIZATION_TYPE_FROM, ORGANIZATION_TYPE_TO, INTERLOCK_TYPE_ID, CREATED_USER_ID)
	VALUES(2,1,1,1,1,2,1);

RENAME COLUMN "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST"."ENTITY_ID" TO "ENTITY_ID_TO";

DROP TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_INTERLOCK_ORGANIZATION";
DROP TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_REGION";
DROP TABLE "MKTG_PLANNING_TOOL"."INTERLOCK_REQUEST_SUBREGION";

-- *************************************************************************************
-- Update schema version

INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-87', 'Interlock Refactor', 'V201711141447__Interlock_Refactor.sql');

COMMIT;