UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 26
WHERE DYNAMIC_FORM_FIELD_ID = 24;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 26
WHERE DYNAMIC_FORM_FIELD_ID = 26;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 26
WHERE DYNAMIC_FORM_FIELD_ID = 27;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 26
WHERE DYNAMIC_FORM_FIELD_ID = 28;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 26
WHERE DYNAMIC_FORM_FIELD_ID = 30;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 27
WHERE DYNAMIC_FORM_FIELD_ID = 55;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 27
WHERE DYNAMIC_FORM_FIELD_ID = 57;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 27
WHERE DYNAMIC_FORM_FIELD_ID = 58;

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET DYNAMIC_FORM_TAB_ID = 27
WHERE DYNAMIC_FORM_FIELD_ID = 59;


-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-186', 'Mooved the old fields related with Physical Events from the Tactics tab to Event Planning Form - L5/L6', 'V201911211635__Changed_Dynamic_Fields_from_Tactics_to_Event_Planning_Form_tab.sql');

COMMIT;
