UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET ORDER_NUMBER = 43
WHERE FIELD_NAME = 'BUSINESS_CASE';

UPDATE "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD"
SET ORDER_NUMBER = 44
WHERE FIELD_NAME = 'EVENT_FOLLOW_UP_ACTIVITIES';

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EVENT_SUMMARY', 'Event Summary', 2, 85, 1, 27, 42, 'textarea');

INSERT INTO "MKTG_PLANNING_TOOL"."DYNAMIC_FORM_FIELD" (FIELD_NAME, FIELD_DISPLAY_NAME, HIERARCHY_LEVEL_ID, CREATED_USER_ID, MANDATORY, DYNAMIC_FORM_TAB_ID, ORDER_NUMBER, FIELD_TYPE)
VALUES ('EVENT_SUMMARY', 'Event Summary', 3, 85, 1, 27, 42, 'textarea');

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-190', 'Add Event Summary to Dynamic Form for HL5 and HL6', 'V202001061600__Add_Event_Summary_dynamic_form_field.sql');

COMMIT;
