CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL2_CATEGORY_OPTION" (
        HL2_CATEGORY_OPTION_ID bigint not null primary key generated by default as IDENTITY,
        ALLOCATION_CATEGORY_OPTION_LEVEL_ID BIGINT NOT NULL,
        AMOUNT DECIMAL(19,2) NOT NULL,
        HL2_ID BIGINT NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        updated tinyint default 0,
        FOREIGN KEY ("ALLOCATION_CATEGORY_OPTION_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"("ALLOCATION_CATEGORY_OPTION_LEVEL_ID"),
        FOREIGN KEY ("HL2_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL2"("HL2_ID"),
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);