CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL3_VERSION" ("HL3_ID" BIGINT CS_FIXED NOT NULL ,
	 "VERSION" INTEGER CS_INT NOT NULL ,
	 "HL3_DESCRIPTION" NVARCHAR(255) NOT NULL ,
	 "BUSINESS_OWNER_ID" BIGINT CS_FIXED NOT NULL ,
	 "ORIGIN_PLAN_ID" BIGINT CS_FIXED,
	 "HL2_ID" BIGINT CS_FIXED NOT NULL ,
	 "CRM_ID" BIGINT CS_FIXED,
	 "HL3_HIERARCHY_ID" BIGINT CS_FIXED,
	 "CREATED_DATE_TZ" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP,
	 "CREATED_USER_ID" BIGINT CS_FIXED NOT NULL ,
	 "HL3_STATUS_DETAIL_ID" BIGINT CS_FIXED,
	 "ACRONYM" NVARCHAR(25) NOT NULL ,
	 "HL3_FNC_BUDGET_TOTAL" DECIMAL(19,
	2) CS_FIXED,
	 "IN_BUDGET" TINYINT CS_INT,
	 "COST_CENTER" NVARCHAR(10),
	 "SHOPPING_CART_APPROVER" NVARCHAR(10),
	 PRIMARY KEY INVERTED VALUE ("HL3_ID",
	 "VERSION")) UNLOAD PRIORITY 5 AUTO MERGE
;
ALTER TABLE "MKTG_PLANNING_TOOL"."HL3_VERSION" ADD FOREIGN KEY ( "CREATED_USER_ID" ) REFERENCES "MKTG_PLANNING_TOOL"."USER" ("USER_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
ALTER TABLE "MKTG_PLANNING_TOOL"."HL3_VERSION" ADD FOREIGN KEY ( "HL3_ID" ) REFERENCES "MKTG_PLANNING_TOOL"."HL3" ("HL3_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
