CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY_OPTION" (
	SEGMENTATION_CATEGORY_OPTION_ID bigint not null primary key generated by default as IDENTITY,
	SEGMENTATION_CATEGORY_ID BIGINT NOT NULL,
	name nvarchar(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
	deleted_token nvarchar(255) null,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
    FOREIGN KEY ("SEGMENTATION_CATEGORY_ID") REFERENCES "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY"("SEGMENTATION_CATEGORY_ID")
);
