CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL2_VERSION" ("HL2_ID" BIGINT CS_FIXED NOT NULL ,
	 "VERSION" INTEGER CS_INT NOT NULL ,
	 "ACRONYM" NVARCHAR(25),
	 "DESCRIPTION" NVARCHAR(255),
	 "BUDGET_YEAR_ID" BIGINT CS_FIXED,
	 "REGION_ID" BIGINT CS_FIXED,
	 "SUBREGION_ID" BIGINT CS_FIXED,
	 "CREATED_DATE_TZ" LONGDATE CS_LONGDATE DEFAULT CURRENT_TIMESTAMP,
	 "CREATED_USER_ID" BIGINT CS_FIXED NOT NULL ,
	 "HL2_BUDGET_TOTAL" DECIMAL(19,
	2) CS_FIXED NOT NULL ,
	 "ORGANIZATION_ACRONYM" NVARCHAR(25),
	 "ORGANIZATION_NAME" NVARCHAR(255),
	 "TEAM_TYPE_ID" BIGINT CS_FIXED DEFAULT 1,
	 "CRT_RELATED" TINYINT CS_INT DEFAULT 0 NOT NULL ,
	 "IMPLEMENT_EXECUTION_LEVEL" TINYINT CS_INT DEFAULT 0 NOT NULL ,
	 "HL1_ID" BIGINT CS_FIXED NOT NULL ,
	 "IN_BUDGET" TINYINT CS_INT NOT NULL ,
	 "ALLOW_AUTOMATIC_BUDGET_APPROVAL" TINYINT CS_INT DEFAULT 0,
	 PRIMARY KEY INVERTED VALUE ("HL2_ID",
	 "VERSION")) UNLOAD PRIORITY 5 AUTO MERGE
;
ALTER TABLE "MKTG_PLANNING_TOOL"."HL2_VERSION" ADD FOREIGN KEY ( "CREATED_USER_ID" ) REFERENCES "MKTG_PLANNING_TOOL"."USER" ("USER_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
ALTER TABLE "MKTG_PLANNING_TOOL"."HL2_VERSION" ADD FOREIGN KEY ( "HL2_ID" ) REFERENCES "MKTG_PLANNING_TOOL"."HL2" ("HL2_ID") ON UPDATE RESTRICT ON DELETE RESTRICT
;
