create column table "MKTG_PLANNING_TOOL"."HL4_PREFILLED"(
        "HL4_PREFILLED_ID" bigint not null primary key generated by default as IDENTITY,
        "ACRONYM" nvarchar(25) not null,
		"CRM_DESCRIPTION" nvarchar(100) not null,
		"DETAILS" nvarchar(3000) not null,
		"BUSINESS_DETAILS" nvarchar(3000) not null,
		
		"CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
		"MODIFIED_DATE_TZ" timestamp,
		"CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,
        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);