create column table "MKTG_PLANNING_TOOL"."IMPORT_HL" (
	import_id bigint not null primary key generated by default as IDENTITY,
	description nvarchar(255),
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "MKTG_PLANNING_TOOL".USER(user_id)
);