CREATE COLUMN TABLE "MKTG_PLANNING_TOOL"."HL3_CATEGORY_OPTION" (
        HL3_CATEGORY_OPTION_ID bigint not null primary key generated by default as IDENTITY,
        ALLOCATION_CATEGORY_OPTION_LEVEL_ID BIGINT NOT NULL,
        AMOUNT DECIMAL(39,3) NOT NULL,
        HL3_ID BIGINT NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 3,
        deleted tinyint default 0,
        updated tinyint default 0,
        FOREIGN KEY ("ALLOCATION_CATEGORY_OPTION_LEVEL_ID") REFERENCES "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"("ALLOCATION_CATEGORY_OPTION_LEVEL_ID"),
        FOREIGN KEY ("HL3_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL3"("HL3_ID"),
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID")
);