create column table "MKTG_PLANNING_TOOL"."HL2_EXPECTED_OUTCOMES" (
        "HL2_EXPECTED_OUTCOMES_ID" bigint not null primary key generated by default as IDENTITY,
        "HL2_ID" bigint NOT NULL,
        "COMMENTS" NVARCHAR(3000) NULL,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "MKTG_PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("HL2_ID") REFERENCES "MKTG_PLANNING_TOOL"."HL2"("HL2_ID")
);