create column table "MKTG_PLANNING_TOOL"."SEGMENTATION_CATEGORY" (
	SEGMENTATION_CATEGORY_ID bigint not null primary key generated by default as IDENTITY,
	name nvarchar(255) NOT NULL,
	ALLOCATION_CATEGORY_ID BIGINT NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
	FOREIGN KEY ("ALLOCATION_CATEGORY_ID") REFERENCES "MKTG_PLANNING_TOOL"."ALLOCATION_CATEGORY"("ALLOCATION_CATEGORY_ID"),
    FOREIGN KEY (created_user_id) REFERENCES "MKTG_PLANNING_TOOL".USER(user_id)
);
